baseURL = 'https://www.keathley.co/'
languageCode = 'en-us'
title = 'keathley.co'
theme = "hugo-blog-awesome"
staticDir = ["static", "images"]

[params]
  defaultColor = "auto"
  mainSections = ["posts"]
  goToTop = true

[params.author]
  name = "Matt Keathley"

[[params.socialIcons]]
name = "github"
url = "https://github.com/mrkeathley"

[[params.socialIcons]]
name = "twitter"
url = "https://x.com/Matt_Keathley"

[[params.socialIcons]]
name = "Rss"
url = "/index.xml"

[[menu.main]]
pageRef = "posts"
name = "Posts"
url = "/posts/"
weight = 10

[[menu.main]]
pageRef = "tags"
name = "Tags"
url = "/tags/"
weight = 20
